// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TowerDefense.Server.Data;

#nullable disable

namespace TowerDefense.Server.Migrations
{
    [DbContext(typeof(GameDBContext))]
    partial class GameDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TowerDefense.Common.Models.Access.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionName")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Access.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Access.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Formation", b =>
                {
                    b.Property<int>("IdPlayer")
                        .HasColumnType("integer");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("integer");

                    b.Property<int>("IdTower")
                        .HasColumnType("integer");

                    b.HasKey("IdPlayer", "SlotIndex");

                    b.HasIndex("IdTower");

                    b.HasIndex("IdPlayer", "SlotIndex", "IdTower")
                        .IsUnique();

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Inventory", b =>
                {
                    b.Property<int>("IdPlayer")
                        .HasColumnType("integer");

                    b.Property<int>("IdTower")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("IdPlayer", "IdTower");

                    b.HasIndex("IdTower");

                    b.ToTable("Inventories", t =>
                        {
                            t.HasCheckConstraint("Ck_Inventory_Quantity", "\"Quantity\" >= 0");
                        });
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BanReason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LoginCount")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerProfile", b =>
                {
                    b.Property<int>("IdPlayer")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.HasKey("IdPlayer");

                    b.ToTable("PlayerProfiles");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerRole", b =>
                {
                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("PlayerRoles");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerStatistic", b =>
                {
                    b.Property<int>("IdPlayer")
                        .HasColumnType("integer");

                    b.Property<int>("Losses")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMatches")
                        .HasColumnType("integer");

                    b.Property<int>("Wins")
                        .HasColumnType("integer");

                    b.HasKey("IdPlayer");

                    b.ToTable("PlayerStatistics");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Tower.Ttower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TowerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("TowerName")
                        .IsUnique();

                    b.ToTable("Towers");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Access.RolePermission", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Access.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowerDefense.Common.Models.Access.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Formation", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Player.Player", "Player")
                        .WithMany("Formations")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowerDefense.Common.Models.Tower.Ttower", "Tower")
                        .WithMany("Formations")
                        .HasForeignKey("IdTower")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Inventory", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Player.Player", "Player")
                        .WithMany("Inventories")
                        .HasForeignKey("IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowerDefense.Common.Models.Tower.Ttower", "Tower")
                        .WithMany("Inventories")
                        .HasForeignKey("IdTower")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tower");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerProfile", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Player.Player", "Player")
                        .WithOne("PlayerProfiles")
                        .HasForeignKey("TowerDefense.Common.Models.Player.PlayerProfile", "IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerRole", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Player.Player", "Player")
                        .WithMany("PlayerRoles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TowerDefense.Common.Models.Access.Role", "Role")
                        .WithMany("PlayerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.PlayerStatistic", b =>
                {
                    b.HasOne("TowerDefense.Common.Models.Player.Player", "Player")
                        .WithOne("PlayerStatistics")
                        .HasForeignKey("TowerDefense.Common.Models.Player.PlayerStatistic", "IdPlayer")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Access.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Access.Role", b =>
                {
                    b.Navigation("PlayerRoles");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Player.Player", b =>
                {
                    b.Navigation("Formations");

                    b.Navigation("Inventories");

                    b.Navigation("PlayerProfiles")
                        .IsRequired();

                    b.Navigation("PlayerRoles");

                    b.Navigation("PlayerStatistics")
                        .IsRequired();
                });

            modelBuilder.Entity("TowerDefense.Common.Models.Tower.Ttower", b =>
                {
                    b.Navigation("Formations");

                    b.Navigation("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
